### ISSUE TITLE
library not found for -lReactNativeFlurry

### ISSUE THREAD

**Issue by akahnn** [flurry/react-native-flurry-sdk#1]
Getting this error after going through installation. 

`ld: library not found for -lReactNativeFlurry clang: error: linker command failed with exit code 1 (use -v to see invocation)`

- The library is linked properly in xcode. (File added to Libraries + Link Binary with Libraries) 
- Using xcworkspace to run project. 
- React Native version: :` "^0.57.5",`
- [React Native Flurry Analytics](https://github.com/xxsnakerxx/react-native-flurry-analytics) works perfectly fine.

**Comment by xnth97** [comment]
Hi, thank you for taking time to reach out. We will release a version to fix it very soon. For now, if you are using Xcode 10, please select `Libraries`->`ReactNativeFlurry.xcodeproj`, go to `Build Settings`, search for `Base SDK` and change it to `iOS`.

<img width="1138" alt="screen shot 2018-11-26 at 11 10 49 am" src="https://user-images.githubusercontent.com/6781789/49036263-1a038380-f16c-11e8-8338-7b5381a5538d.png">

**Comment by poting-oath** [comment]
New 1.3.0 just released with the fix. Thanks!

**Comment by poting-oath** [comment]
@akahnn Does the new release resolve your build issue? Thanks!

**Comment by akahnn** [comment]
@poting-oath Yes, it works now, thank you.
