### ISSUE TITLE
How we can get payload data at the time of click tray when app is closed in Android push notification?

### ISSUE THREAD

**Issue by saravananangu** [flurry/react-native-flurry-sdk#12]
**The Problem is while i m clicking the tray, i didn't not get payload data console(debug mode) or alert. At the time app is closed**

`Flurry.addMessagingListener((message) => {
});`

not working

**Comment by poting-oath** [comment]
Duplicate, move to https://github.com/flurry/react-native-flurry-sdk/issues/11
