### ISSUE TITLE
How to use flurry for cumulative data like total amount of moneys users spent?

### ISSUE THREAD

**Issue by pouya92** [flurry/react-native-flurry-sdk#16]
Hi, thank you for your perfect library, I need to know sum of money users spent daily on my app. how can I achieve that with your api's,
Also I want to log an event with more than one parameters so is this the write way?
```
 Flurry.logEvent(eventType, {itemType : eventParam , itemID : eventParam2, itemCost : eventParam3, itemCurrency : eventParam4})
```

**Comment by poting-oath** [comment]
@pouya92 To get the cumulative data, or any numerical measurements, please use Flurry console by,

1. Click on Explorer tab
2. Use Measures under Data Analysis category
3. In your query, select "Event Parameter - Numeric - Sum, Avg, etc..." for Metrics

**Comment by poting-oath** [comment]
Please check the Flurry Doc site for more information. Thanks!
https://developer.yahoo.com/flurry/docs/
