### ISSUE TITLE
React/RCTDefines.h file not found

### ISSUE THREAD

**Issue by sasasim** [flurry/react-native-flurry-sdk#2]
Hello,

I am trying to add this library on my project for two days and it is always getting failed.
I am using react-native: 0.57.1 and react-native-cli: 2.0.1
Please check about the screenshot below.

Regards,
Dima

![screen shot 2018-12-10 at 11 42 51 am](https://user-images.githubusercontent.com/28338990/49720426-c0717d80-fc70-11e8-9645-1b6d6afb2377.png)

**Comment by xnth97** [comment]
Hi Dima,

Sorry to hear that you are having issues with Flurry. Unfortunately we are unable to reproduce the issue using react-native 0.57.1 and react-native-cli 2.0.1. Could you please share more information, like did you use CocoaPods for React? 

In addition, you may want to try the following:

1. Check if React path is correctly included in the Header Search Paths of ReactNativeFlurry.xcodeproj
![screen shot 2018-12-10 at 10 57 38 am](https://user-images.githubusercontent.com/6781789/49754479-0592b100-fc6b-11e8-83b1-62611c220420.png)

2. Clear the build folder (Command + Shift + K) and do a clean build. 

3. Relink react-native-flurry-sdk by executing `react-native unlink react-native-flurry-sdk && react-native link react-native-flurry-sdk`

4. Update react-native to the latest version 0.57.7 if it's okay for you (be very careful about this though).

**Comment by sasasim** [comment]
Sure, All configurations are same with that but it doesn't work. My project is expo

**Comment by xnth97** [comment]
If you are using expo, could you please try adding `$(SRCROOT)/../../../ios/Pods/Headers/Public` to the Header Search Paths mentioned above and set it to `recursive`? 

Reference: [Changing Native Dependencies](https://docs.expo.io/versions/latest/guides/expokit.html#ios)

**Comment by sasasim** [comment]
Thank @xnth97, It is working now
