### ISSUE TITLE
Reinitializing flurry on the fly

### ISSUE THREAD

**Issue by pavermakov** [flurry/react-native-flurry-sdk#22]
**Describe the bug**
This is not a bug, but rather a question. What would happen if I invoke Flurry.Builder() multiple times throughout the app with different api keys? Will flurry pickup the api key change and send events to a correct account?

**This Bug is About**
Please choose the closest item by replacing `[ ]` with `[x]`.
- [ ] Integration
- [x] Analytics
- [ ] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [ ] Other

**Platform**
Please choose the platform(s) that you are having the issue by replacing `[ ]` with `[x]`.
- [x] Android
- [x] iOS
- [ ] tvOS

**Environment**
Please tell us the versions of SDKs you are using. If you are not sure about React Native version, you can run `react-native --version` under your project.
* React Native version: 0.62.2
* react-native-flurry-sdk version: 5.5.0

**Comment by poting-oath** [comment]
No, Flurry does not support multiple FlurryAgent initialization. When FlurryAgent.Builder() been called the second time, it will just return immediately. Therefore, the new API Key will not be reset.

With the following message in the adb log.
"Invalid call to Init. Flurry is already initialized"

**Comment by pavermakov** [comment]
@poting-oath thanks!
