### ISSUE TITLE
Upgrade from 5.5.0 to 6.0.0 causes "[!] [Xcodeproj] Generated duplicate UUIDs" error

### ISSUE THREAD

**Issue by timetarget** [flurry/react-native-flurry-sdk#24]
Upgrade from 5.5.0 to 6.0.0 causes _[!] [Xcodeproj] Generated duplicate UUIDs_ on running pod install.
react-native 0.62.2

**This Bug is About**
- [ ] Integration
- [ ] Analytics
- [ ] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [x] Other

**Platform**
- [ ] Android
- [x] iOS
- [ ] tvOS

**Additional context**
Are you using Flurry Push/Messaging? Yes / **No**
(iOS) Are you using CocoaPods for React Native integration? **Yes** / No

Here is a part of the output:

> [!] [Xcodeproj] Generated duplicate UUIDs:
> 
> PBXFileReference --Pods.xcodeproj/mainGroup/children/children:children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Analytics,isa:PBXGroup,name:Analytics,path:Analytics,sourceTree:<group>,,children:|,|,|,|,|,displayName:CocoaAsyncSocket,isa:PBXGroup,name:CocoaAsyncSocket,path:CocoaAsyncSocket,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:CocoaLibEvent,isa:PBXGroup,name:CocoaLibEvent,path:CocoaLibEvent,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:DoubleConversion,isa:PBXGroup,name:DoubleConversion,path:DoubleConversion,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Flipper,isa:PBXGroup,name:Flipper,path:Flipper,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Flipper-DoubleConversion,isa:PBXGroup,name:Flipper-DoubleConversion,path:Flipper-DoubleConversion,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Flipper-Folly,isa:PBXGroup,name:Flipper-Folly,path:Flipper-Folly,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Flipper-Glog,isa:PBXGroup,name:Flipper-Glog,path:Flipper-Glog,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|,displayName:Flipper-PeerTalk,isa:PBXGroup,name:Flipper-PeerTalk,path:Flipper-PeerTalk,sourceTree:<group>,,children:|,|,|,|,|,|,|,|,|...

**Comment by hantao-flurrydev** [comment]
Hi @timetarget, this looks like an cocoapods issue for me as similar issues can be found [online](https://github.com/ivpusic/react-native-image-crop-picker/issues/680).

**Comment by poting-oath** [comment]
Cocoapods issue as described.
