### ISSUE TITLE
Crashes on iOS in production

### ISSUE THREAD

**Issue by AlanKeiss** [flurry/react-native-flurry-sdk#25]
Since the 18th september 2020, we notice a lot of crashes on Crashlytics coming from Flurry SDK in most of our apps that use react-native-flurry-sdk 4.1.0 or lower versions. Most of these apps have not been updated in the last 6 months. We have a lot of apps and could not afford an update for each of them.

Here is the meaningful part of the stack trace : 

Fatal Exception: NSInvalidArgumentException
-[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: fl.TransactionIdentifier)
0  CoreFoundation                 0x19cf1a5ac __exceptionPreprocess
1  libobjc.A.dylib                0x1b0f9442c objc_exception_throw
2  CoreFoundation                 0x19cf894cc -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x19cf9580c -[__NSDictionaryM setObject:forKey:].cold.3
4  CoreFoundation                 0x19cdfed44 -[__NSDictionaryM setObject:forKey:]
5  APP_NAME                         0x10468bc40 -[FlurryRecordTransactionRequestManager eventParamsWithTransaction:]
6  APP_NAME                         0x10468b61c __76-[FlurryRecordTransactionRequestManager doRecordTransaction:statusCallback:]_block_invoke_3

**This Bug is About**
- [ ] Integration
- [ ] Analytics
- [ ] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [x] Other

**Platform**
- [ ] Android
- [x] iOS
- [ ] tvOS

**Environment**
* React Native version: 0.60.5
* react-native-flurry-sdk version: 4.1.0

**Additional context**
Are you using Flurry Push/Messaging?  No
(iOS) Are you using CocoaPods for React Native integration? Yes

Thank you

**Comment by poting-oath** [comment]
@AlanKeiss Please try to upgrade your plugin. The one, 4.1.0, was released 13 months ago and we have lots of changes since then. And iOS also introduced many new policies. Thanks!

**Comment by hantao-flurrydev** [comment]
@AlanKeiss thanks for sharing this issue with us. After investigation, the issue seems also available in the newest iOS SDK version, so please do not upgrade the plugin until we release a new patch with the fix for this issue. We will let you know for any update on this, and thanks again for your patience.

**Comment by hantao-flurrydev** [comment]
@AlanKeiss Please upgrade to the newer versions of plugin, which contains the new API levels that resolves issue like this.

**Comment by poting-oath** [comment]
Close it because we already have fix long ago.
