### ISSUE TITLE
Xcode failing to build for simulator

### ISSUE THREAD

**Issue by chrisid** [flurry/react-native-flurry-sdk#26]
**Describe the bug**
Xcode build fails when trying on Simulator

**This Bug is About**
- [X] Integration

**Platform**
- [X] iOS

**Environment**
Please tell us the versions of SDKs you are using. If you are not sure about React Native version, you can run `react-native --version` under your project.
* React Native version: 0.63.2
* react-native-flurry-sdk version: 6.1.0

**To Reproduce**
1. From XCode Select a Simulator and build

**Screenshots**

**Additional context**
Are you using Flurry Push/Messaging?
No

(iOS) Are you using CocoaPods for React Native integration?
Yes

**ld: in /ios/Pods/Flurry-iOS-SDK/FlurryConfig/libFlurryConfig_11.1.0.a(libFlurryConfig.a-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/ios/Pods/Flurry-iOS-SDK/FlurryConfig/libFlurryConfig_11.1.0.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

**Comment by hantao-flurrydev** [comment]
Hi @chrisid, are you using xcode12?

**Comment by chrisid** [comment]
> Hi @chrisid, are you using xcode12?

Yes, I am. I'm sorry I forgot to mention that.

**Comment by hantao-flurrydev** [comment]
@chrisid, we are going to release binary build with xcode12 which will resolve this issue. Current SDK doesn't support xcode12 build. Sorry for this inconvenience.

**Comment by poting-oath** [comment]
@chrisid We have released an xcode12 compatible build v6.1.9. Please try to use it with xcode12. Thanks!
https://www.npmjs.com/package/react-native-flurry-sdk/v/6.1.9

**Comment by poting-oath** [comment]
Closed because fix is available in release v6.1.9.
