### ISSUE TITLE
Android icon missing 

### ISSUE THREAD

**Issue by GopalAdappt** [flurry/react-native-flurry-sdk#27]

**Comment by GopalAdappt** [comment]
We are facing some issues in Android regarding receiving notification icon is in Grey box to a specific device module as mentioned below. 

package.json
“react": "16.8.3",
"react-native": "0.59.10",
"react-native-flurry-sdk": "^6.1.0"



Devices
1. Lenovo
Model: A7010a48
OS: 6

2. Redmi
Model: RedmiNote 5 Pro
![A7010a48](https://user-images.githubusercontent.com/64896659/97899847-d48c5f80-1d5f-11eb-8291-76862f14c27a.jpg)

OS: 9

**Comment by poting-oath** [comment]
This is a feature we already resolved in https://github.com/flurry/react-native-flurry-sdk/issues/7.

When you initialize Flurry Messaging, you can specify your `FlurryMarketingOptions`.
Inside your `FlurryMarketingOptions`, you can define your notification icon there.

Please check our README,
```
.withMessaging(true, options_or_listener) // optional user's native `FlurryMarketingOptions` or `FlurryMessagingListener`. 
```

I.e.,
1. Add the following dependency in your android's `build.gradle`:
   ```
   implementation 'com.flurry.android:marketing:12.9.0'
   ```
2. Import `FlurryMarketingOptions` in your `MainApplication`:
   ```
   import com.flurry.android.marketing.FlurryMarketingOptions;
   ```
3. Define your `FlurryMarketingOptions` with the icon you want to show:
   ```
   FlurryMarketingOptions messagingOptions = new FlurryMarketingOptions.Builder()
           .setupMessagingWithAutoIntegration()
           .withDefaultNotificationIconResourceId(R.mipmap.ic_launcher_round)   // your icon here.
           // Define more if needed
           // .withDefaultNotificationChannelId(NOTIFICATION_CHANNEL_ID)
           // .withDefaultNotificationIconAccentColor(getResources().getColor(R.color.colorPrimary))
           // .withFlurryMessagingListener(messagingListener)
           .build();
   ```
4. Finally enable Flurry Messaging with your options:
   ```
    new FlurryModule.Builder()
              .withLogEnabled(true)
              .withLogLevel(Log.VERBOSE)
              .withMessaging(true, messagingOptions)
              .build(this, YOUR_APK_KEY);   
   ```

**Comment by poting-oath** [comment]
If the above approach does not resolve your issue, means your Android icon resource is not available for the specific devices.

I.e., your Android resources probably does not give a general definition of this icon.

All of the approach are pure Android codes. Please check your icon Android resources.

**Comment by poting-oath** [comment]
@GopalAdappt Do you resolve your app icon issue by checking the icon resources? Thanks!

**Comment by poting-oath** [comment]
Close it as the complete steps to set Messaging is described in the React Native Tutorial.
https://github.com/flurry/React-Native-Tutorial#users-native-flurry-push-options-or-listener
