### ISSUE TITLE
null is not an object (evaluating RNFlurryAnalytics)

### ISSUE THREAD

**Issue by supagu** [flurry/react-native-flurry-sdk#29]
**Describe the bug**
Flurry does not appear to be working correctly.

    pod install

results in the following error:

    [!] No podspec found for `react-native-flurry-sdk` in `../node_modules/react-native-flurry-sdk/ios`
    
    [!] use_native_modules! skipped the react-native dependency 'react-native-flurry-analytics'. No podspec file was found.
        - Check to see if there is an updated version that contains the necessary
        podspec file
        - Contact the library maintainers or send them a PR to add a podspec. The
        react-native-webview podspec is a good example of a package.json driven
        podspec. See
        https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
        - If necessary, you can disable autolinking for the dependency and link it
        manually. See
        https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**This Bug is About**
Please choose the closest item by replacing `[ ]` with `[x]`.
- [ ] Integration
- [x] Analytics
- [ ] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [ ] Other

**Platform**
Please choose the platform(s) that you are having the issue by replacing `[ ]` with `[x]`.
- [ ] Android
- [x] iOS
- [ ] tvOS

**Environment**
react-native-cli: 2.0.1
react-native: 0.63.4

"react-native-flurry-analytics": "^3.0.3",

**To Reproduce**

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2021-01-11 at 13 30 53](https://user-images.githubusercontent.com/11153232/104143924-4f818e80-5411-11eb-9e3c-815ce07c9fee.png)

**Additional context**
Are you using Flurry Push/Messaging? No
(iOS) Are you using CocoaPods for React Native integration? Yes

**Comment by poting-oath** [comment]
You are not using our plugin. Our product is "react-native-flurry-sdk". And you are using "react-native-flurry-analytics": "^3.0.3".

Please follow the docs in https://www.npmjs.com/package/react-native-flurry-sdk, to switch to our tool. Thanks!

**Comment by poting-oath** [comment]
E.g., "react-native-flurry-sdk": "^6.2.0",

**Comment by poting-oath** [comment]
Closed it because it's for different plugin. Please update to use ours. Thanks!
