### ISSUE TITLE
logEvent does not save params

### ISSUE THREAD

**Issue by chrisid** [flurry/react-native-flurry-sdk#30]
**Describe the bug**
I'm unsure if this is an issue with the library or with the dashboard.
I cant get events parameters to be logged, been trying for weeks now.

`Flurry.logEvent('test_event', {'theparam': '1234'});`

**This Bug is About**
Please choose the closest item by replacing `[ ]` with `[x]`.
- [X] Analytics
- [?] Flurry Website/Dashboard

**Platform**
Please choose the platform(s) that you are having the issue by replacing `[ ]` with `[x]`.
- [X] iOS

**Environment**
Please tell us the versions of SDKs you are using. If you are not sure about React Native version, you can run `react-native --version` under your project.
* React Native version: 0.63.2
* react-native-flurry-sdk version: 6.2.0

**Comment by poting-oath** [comment]
I just confirmed that the plugin does pass through all params to the underneath SDK without any issues. And see all of the logging params from the UI.

Please first to navigate the features in the Flurry UI. Some tabs you can check are,
- Under Analytics tab
  - Events
    - Parameter Trend
    - Parameter Distribution

Or use the params for measurement
- Under Explorer tab
  - Data Analytics
    - Measures

**Comment by chrisid** [comment]
> I just confirmed that the plugin does pass through all params to the underneath SDK without any issues. And see all of the logging params from the UI.
> 
> Please first to navigate the features in the Flurry UI. Some tabs you can check are,
> 
> * Under Analytics tab
>   
>   * Events
>     
>     * Parameter Trend
>     * Parameter Distribution
> 
> Or use the params for measurement
> 
> * Under Explorer tab
>   
>   * Data Analytics
>     
>     * Measures

You are absolutely right, thank you very much for the info. I wasn't looking at the correct flow.
