### ISSUE TITLE
Retrieve FCM Device Token

### ISSUE THREAD

**Issue by nidhinprathap** [flurry/react-native-flurry-sdk#36]
**Describe the bug**
Is there a way to retrieve the device push notification token? Need to retrieve the token and save it.

**This Bug is About**
Please choose the closest item by replacing `[ ]` with `[x]`.
- [ ] Integration
- [ ] Analytics
- [x] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [ ] Other

**Platform**
Please choose the platform(s) that you are having the issue by replacing `[ ]` with `[x]`.
- [x] Android
- [ ] iOS
- [ ] tvOS

**Environment**

* React Native version: 0.63.3
* react-native-flurry-sdk version: 6.4.0
**Additional context**
Are you using Flurry Push/Messaging? Yes 

Below Method "onTokenRefresh" gets fired before I can add a messaging listener, so the event is never triggered as **sEnableMessagingListener** false at that time.

```
@Override
        public void onTokenRefresh(String token) {
            if (sEnableMessagingListener && (sReactApplicationContext != null)) {
                sendEvent(EventType.TokenRefresh, token);
            }
        }
```

**Comment by poting-oath** [comment]
@nidhinprathap Thanks for the info!
We will keep the token when onTokenRefresh been called. Then send event with the token to the React Native listener when registering.

**Comment by nidhinprathap** [comment]
@poting-oath   Yes, that will helpful, or even exposing a method to get the token from the native side also will be good, so that I can retrieve the token whenever I want. This would require saving the device token in local storage or sharedpref.

**Comment by poting-oath** [comment]
@nidhinprathap I have fixed the token refresh callback. The fix will be available in the next release.

**Comment by nidhinprathap** [comment]
@poting-oath  when can I expect the release? or can a patch be released ?

**Comment by poting-oath** [comment]
@nidhinprathap We plan to release a new build in the next few weeks. However you can use the attached patch to update your local node_modules/react-native-flurry-sdk.
[RNToken.patch.gz](https://github.com/flurry/react-native-flurry-sdk/files/6516567/RNToken.patch.gz)

**Comment by poting-oath** [comment]
@nidhinprathap react-native-flurry-sdk 7.0.0 released with the fix. Thanks!
