### ISSUE TITLE
problem with install CocoaPods

### ISSUE THREAD

**Issue by donchop** [flurry/react-native-flurry-sdk#39]
**Describe the bug**
When I install react-native-flurry-sdk - have problem with installation pods for IOS. Also at  readme  and  here in documentation(https://developer.yahoo.com/flurry/docs/integrateflurry/ios/). Wrote, that need add some code to "podfile", like this "pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod" or if you need push messages - "another code to podfile", but now "podfile" have another structure and you can't do this how I understand.
Also, I not yet tried to install previous version, may be it will work...

**This Bug is About**
Please choose the closest item by replacing `[ ]` with `[x]`.
- [X] Integration
- [ ] Analytics
- [ ] Messaging/Push
- [ ] Remote Configuration
- [ ] Flurry Website/Dashboard
- [ ] Other

**Platform**
Please choose the platform(s) that you are having the issue by replacing `[ ]` with `[x]`.
- [ ] Android
- [X] iOS
- [ ] tvOS

**Environment**
Please tell us the versions of SDKs you are using. If you are not sure about React Native version, you can run `react-native --version` under your project.
* React Native version: 0.64.2
* react-native-flurry-sdk version: 7.1.1

**To Reproduce**
1. install react-native-flurry-sdk, and write pod install at ios folder.
2. ...
3. ...

**Screenshots**
<img width="1083" alt="Screenshot 2022-01-13 at 15 20 21" src="https://user-images.githubusercontent.com/14181533/149337776-16afe32b-6f1e-4d77-b215-df3821c84f1d.png">
<img width="1094" alt="Screenshot 2022-01-13 at 15 20 37" src="https://user-images.githubusercontent.com/14181533/149337809-8f5a4326-eab9-42e2-b57b-5e7e0ec16e10.png">
<img width="1094" alt="Screenshot 2022-01-13 at 15 20 46" src="https://user-images.githubusercontent.com/14181533/149337836-a93141f6-4066-4837-a758-ae8b69e75d7c.png">
<img width="1104" alt="Screenshot 2022-01-13 at 15 20 58" src="https://user-images.githubusercontent.com/14181533/149337847-0bd3166c-95b1-4f06-bed2-43ec35ce1d3e.png">

**Additional context**
Are you using Flurry Push/Messaging? No
(iOS) Are you using CocoaPods for React Native integration? Yes

**Comment by donchop** [comment]
Problem was on Mac m1, on mac-mini with intel - all good

**Comment by hantao-flurrydev** [comment]
Hi @donchop, for me just switch to Rosetta and re-setup cocoapods will work. So `gem uninstall -aIx` and then changing the "terminal" to work with Rosetta. Then do a clean up `brew cleanup -d -v` and re-install cocoapods under ARM `arch -arm64 brew install cocoapods`. Also refer to some other forem: https://github.com/CocoaPods/CocoaPods/issues/10518.

**Comment by donchop** [comment]
@hantao-flurrydev  Thanks, it's worked !
