### ISSUE TITLE
build error with typescript in version 2.1.0

### ISSUE THREAD

**Issue by wangzhiqiang** [flurry/react-native-flurry-sdk#5]
`node_modules/react-native-flurry-sdk/index.d.ts(202,66): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).`

**Comment by poting-oath** [comment]
@wangzhiqiang Thanks for the feedback! Could you please info us what IDE/Editor tool you are using to produce this error?

**Comment by flurrydev** [comment]
Will release new version soon with the fix; update to `Promise<object>`.

**Comment by wangzhiqiang** [comment]
vscode and web storm

**Comment by flurrydev** [comment]
@wangzhiqiang We just released a new version 3.0.0 with the fix. Thanks a lot for your great feedback!
