### ISSUE TITLE
Loading application from coldstart doesnt trigger message listener

### ISSUE THREAD

**Issue by thessler27** [flurry/react-native-flurry-sdk#6]
When entering the application from a push notification with the app killed, the `Flurry.addMessagingListener` doesn't trigger the push notification. Is there a way to get access to a push notification from coldstart?

**Comment by poting-oath** [comment]
Thanks for the report!
Yes, this is a known issue/behavior. The "user" listener is written from the JavaScript side, while the Flurry Push is on the Android native side. When app is gone, all JavaScript is not active. Hence when Message comes, we can only trigger Android platform, but not the inactive React Native.

**Comment by poting-oath** [comment]
The workaround is to put your handling in the Android Application class, `MainApplication.java`. Then when Message comes, the native Android is active to handle it.

**Comment by thessler27** [comment]
Thanks for the quick response! I've done this for android, but is there a workaround for iOS?

**Comment by poting-oath** [comment]
Based on your feedback, we will add an API (Android native) in `FlurryModule`.  When you need to handle from cold start as well, you can just pass your listener in `withMessaging` method.

**Comment by poting-oath** [comment]
Let me check on the iOS side.

**Comment by thessler27** [comment]
Thanks for looking into it. Really appreciate it 👍

**Comment by poting-oath** [comment]
@thessler27 In the next release, iOS will allow users to initialize Flurry Push natively in `UIApplication` as well to fix the cold start issue. Thanks a lot for your feedback!

**Comment by thessler27** [comment]
@poting-oath really appreciate you guys looking into this! thanks again.

**Comment by flurrydev** [comment]
@thessler27 We just released a new version 3.2.0 with the feature that allows optional user's native `FlurryMarketingOptions` or `FlurryMessagingListener`. Thanks a lot for your great feedback!

**Comment by poting-oath** [comment]
@thessler27 We just released a new version 3.2.0 with the feature that allows optional user's native `FlurryMarketingOptions` or `FlurryMessagingListener`. Thanks a lot for your great feedback!

**Comment by poting-oath** [comment]
For iOS, we also support Flurry Push initialization from AppDelegate to handle notifications from a cold start. Please refer to README for detailed instruction.
