### ISSUE TITLE
Apple tvOS support

### ISSUE THREAD

**Issue by jakes-rm** [flurry/react-native-flurry-sdk#8]
Hi, we're trying to add this library to an Apple TV app however we're getting the error:

`undefined is not an object (evaluating 'ReactNativeFlurry.initBuilder')`

It's working on iOS and Android TV but not having any luck with tvOS. I can see that the native Flurry SDK supports tvOS, does this react native module provide support as well?

Thanks

**Comment by xnth97** [comment]
Hi,

Thank you for using react-native-flurry-sdk! Currently we don't have support for tvOS. We will investigate into this so please stay tuned!

**Comment by jakes-rm** [comment]
Okay, thanks for the response. Will keep an eye out!

**Comment by poting-oath** [comment]
@jakes-rm We just released a new version 3.6.0 with the tvOS support. Thanks a lot for your great feedback!
