### ISSUE TITLE
ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement.

### ISSUE THREAD

**Issue by markymc** [flurry/react-native-flurry-sdk#9]
I just added this SDK to my existing RN project and put up a TestFlight build. I then received an email from Apple saying:

`ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement.`

However, I don't want to use push notifications at the moment. Is there some way to avoid this?

**Comment by xnth97** [comment]
Hi @markymc ,

Thank you for using Flurry! Could you please check the following:

* Did you enable "Push Notifications" in Xcode's Capabilities tab?
* Did you enable "Remote Notifications" in Background Modes?
* Do you have `.withMessaging(true)` when initializing Flurry.Builder?
* Did you call `[ReactNativeFlurry enableMessaging] in native code`?
* Did you implemented `didRegisterForRemoteNotificationsWithDeviceToken:` in AppDelegate?

Please let me know if the problem still occurs. Thank you!

**Comment by markymc** [comment]
@xnth97 Thanks for your quick reply.

> Did you enable "Push Notifications" in Xcode's Capabilities tab?
> Did you enable "Remote Notifications" in Background Modes?

No I didn't. I just double checked and they're both disabled. 

> Do you have .withMessaging(true) when initializing Flurry.Builder?

No, it's:

```
  new Flurry.Builder()
    .withCrashReporting(true)
    .withLogEnabled(true)
    .withLogLevel(Flurry.LogLevel.DEBUG)
    .build(FLURRY_ANDROID_API_KEY, FLURRY_IOS_API_KEY);
```

> Did you call [ReactNativeFlurry enableMessaging] in native code?
> Did you implement didRegisterForRemoteNotificationsWithDeviceToken: in AppDelegate?

No and no.

> Please let me know if the problem still occurs. Thank you!

As nothing mentioned above needed to change, the problem still exists. 

Thanks!

**Comment by xnth97** [comment]
Hi @markymc ,

Thank you so much for your reply! Sorry for any inconvenience this may cause. We are investigating into this and will let you know once we have a solution.

**Comment by xnth97** [comment]
Hi @markymc ,

We just released a version which contains the fix. Please re-link the RN sdk

```sh
react-native unlink react-native-flurry-sdk && react-native link react-native-flurry-sdk
```

and type n while being asked if you need to integrate Flurry Push. This will guarantee that push related code won't be linked to your project. Please let me know if the problem still occurs. Thank you very much for your feedback!

**Comment by markymc** [comment]
@xnth97 Thanks very much. We'll update to that then. 👍

**Comment by rci20021028** [comment]
I had the same error.
